spring:
  datasource: # 데이터 베이스 연결 설정
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        # 실행되는 쿼리 콘솔 출력
        show_sql: true
        # 콘솔 창에 출력되는 쿼리를 가독성 좋게 포맷팅
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace